name: AI PR Review (Caller)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

#jobs for github
jobs:
  ai-pr-review:
    uses: PR-REVIEW-ORGANIZATION/Agent-Repo/.github/workflows/reusable-pr-ai-review.yml@main
    with:
      repository: ${{ github.repository }}
      pr_number: ${{ github.event.pull_request.number }}
      openai_model: gpt-5-mini
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
